name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: | 
          echo "Hello, World!"
      - name: date
        run: | 
          date
          - name: print date
      - name: list files
        run: | 
          ls
          - name: list files in the current directory